name: $(date:yyyyMMdd)$(rev:.rr)

pr:
  - master

trigger:
  - master

stages:
  - stage: build
    jobs:
      - job: run_build
        steps:
          - script: dotnet build
  - stage: test
    jobs:
      - job: run_tests
        steps:
          - script: dotnet test
  - stage: analyze
    jobs:
      - job: run_analysis
        pool:
          vmImage: ubuntu-18.04
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'Install SonarScanner'
            inputs:
              command: custom
              custom: tool
              arguments: 'install --global dotnet-sonarscanner'
          - script: |
              dotnet sonarscanner begin /k:"tylermart" /o:"tylermart-dev" /d:sonar.login=$(SonarToken) /d:sonar.host.url="https://sonarcloud.io/"
              dotnet build
              dotnet sonarscanner end /d:sonar.login=$(SonarToken)
